[package]
name = "siliconsneaker2"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
compile-time = "0.2.0"
fitparser = "0.10.0"
glib = "0.21.5"
gtk4 = "0.10.2"
libshumate = "0.7.0"
plotters = "0.3.7"
plotters-cairo = "0.8.0"
semver = "1.0.27"
serde = "1.0.228"
toml = "0.9.8"


